theme = "gallery"
title = "Natalie Kim"
baseURL = "https://npt4li6.github.io"
languageCode = "en-us"

[taxonomies]
  category = "categories"

[params]
  customCSS = ["css/custom.css"]

[params.socialIcons]
  instagram = "https://www.instagram.com/natalieckim"
  linkedin = "https://www.linkedin.com/in/nataliekim161"

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/categories/Blog/"
  weight = 2

[[menu.main]]
  name = "Photo Gallery"
  url = "/categories/Photo-Gallery/"
  weight = 3


[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 100